swagger: "2.0"
info:
  version: "0.0.1"
  title: "DealsBro Swagger UI"
host: "dealsbro-api.kevc.workers.dev"
basePath: "/"
schemes:
- "https"
- "http"
paths:
  /deals:
    get:
      tags:
      - "deals"
      summary: "Get all deals"
      responses:
        "200":
          description: "List of deals"
    post:
      tags:
      - "deals"
      summary: "Add a new deal"
      parameters:
      - in: "body"
        name: "body"
        description: "Deal payload"
        required: true
        schema: 
          $ref: "#/definitions/Deal"
      responses:
        "201":
          description: "Deal has been added"
  /deals/{dealId}:
    get:
      tags:
      - "deals"
      summary: "Get single deal"
      parameters:
      - name: "dealId"
        in: "path"
        description: "Deal ID"
        required: true
        type: "string"
      responses:
        "200":
          description: "Deal"
    put:
      tags:
      - "deals"
      summary: "Update single deal"
      parameters:
      - name: "dealId"
        in: "path"
        description: "Deal ID"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Deal payload"
        required: true
        schema: 
          $ref: "#/definitions/Deal"
      responses:
        "200":
          description: "Deal has been updated"
    delete:
      tags:
      - "deals"
      summary: "Delete single deal"
      parameters:
      - name: "dealId"
        in: "path"
        description: "Deal ID"
        required: true
        type: "string"
      responses:
        "204":
          description: "Deal has been deleted"
          
          
  /organisations:
    get:
      tags:
      - "organisations"
      summary: "Get all organisations"
      responses:
        "200":
          description: "List of organisations"
    post:
      tags:
      - "organisations"
      summary: "Add a new organisation"
      parameters:
      - in: "body"
        name: "body"
        description: "Organisation payload"
        required: true
        schema: 
          $ref: "#/definitions/Organisation"
      responses:
        "201":
          description: "Organisation has been added"
          
  /organisations/{orgId}:
    get:
      tags:
      - "organisations"
      summary: "Get single organisation"
      parameters:
      - name: "orgId"
        in: "path"
        description: "Organisation ID"
        required: true
        type: "string"
      responses:
        "200":
          description: "Organisation"
    put:
      tags:
      - "organisations"
      summary: "Update single organisation"
      parameters:
      - name: "orgId"
        in: "path"
        description: "Organisation ID"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Organisation payload"
        required: true
        schema: 
          $ref: "#/definitions/Organisation"
      responses:
        "200":
          description: "Organisation has been updated"
    delete:
      tags:
      - "organisations"
      summary: "Delete single organisation"
      parameters:
      - name: "orgId"
        in: "path"
        description: "Organisation ID"
        required: true
        type: "string"
      responses:
        "204":
          description: "Organisation has been deleted"
          
  /outlets:
    get:
      tags:
      - "outlets"
      summary: "Get all outlets"
      responses:
        "200":
          description: "List of outlets"
    post:
      tags:
      - "outlets"
      summary: "Add a new outlet"
      parameters:
      - in: "body"
        name: "body"
        description: "Outlet payload"
        required: true
        schema: 
          $ref: "#/definitions/Outlet"
      responses:
        "201":
          description: "Outlet has been added"
          
  /outlets/{outletId}:
    get:
      tags:
      - "outlets"
      summary: "Get single outlet"
      parameters:
      - name: "outletId"
        in: "path"
        description: "Outlet ID"
        required: true
        type: "string"
      responses:
        "200":
          description: "Outlet"
    put:
      tags:
      - "outlets"
      summary: "Update single outlet"
      parameters:
      - name: "outletId"
        in: "path"
        description: "Outlet ID"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Outlet payload"
        required: true
        schema: 
          $ref: "#/definitions/Outlet"
      responses:
        "200":
          description: "Outlet has been updated"
    delete:
      tags:
      - "outlets"
      summary: "Delete single outlet"
      parameters:
      - name: "outletId"
        in: "path"
        description: "Outlet ID"
        required: true
        type: "string"
      responses:
        "204":
          description: "Outlet has been deleted"
      
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Deal:
    type: "object"
    properties:
      title:
        type: "string"
      description:
        type: "string"
      companyId:
        type: "string"
      startDT:
        type: "string"
      endDT:
        type: "string"
      outletIds:
        type: "array"
        items:
          type: "string"
  Organisation:
    type: "object"
    properties:
      name:
        type: "string"
  Outlet:
    type: "object"
    properties:
      name:
        type: "string"
      companyId:
        type: "string"
      address:
        type: "string"
      postalCode:
        type: "string"
    
      